version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
  target_branch: "dev"
  open-pull-requests-limit: 10
  labels:
      - "dependencies"
      - "dependabot"
  commit-message:
      prefix: "build"
      include: "scope"
