version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  target_branch: "dev"
  automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
  open-pull-requests-limit: 10
  default_labels:
      - "dependencies"
      - "dependabot"
  commit_message:
      prefix: "build"
      include_scope: true
