name: Node.js CI

on:
  push:
    branches: [alpha, beta, rc, main]

env:
  NODE_VERSION: "14.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Cache yarn
      uses: c-hive/gha-yarn-cache@v2

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Run commitlint
      if: "!contains(github.event.commits[0].message, '[skip ci]')"
      run: yarn commitlint --from=HEAD~1

    - name: Run lint
      run: yarn lint

    - name: Run tests
      run: yarn test:ci

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Cache yarn
      uses: c-hive/gha-yarn-cache@v2

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Release new version
      env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release

  rebase-dev:
    needs: [build, release]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Extract branch name
      uses: vazco/github-actions-branch-name@v1
      id: branch

    - name: Rebase ${{ steps.branch.outputs.branch_name }} onto dev
      uses: ./.github/actions/rebase-branch
      with:
        source: ${{ steps.branch.outputs.branch_name }}
        target: dev
