name: Node.js CI

on:
  push:
    branches: [alpha, beta, rc, main]

env:
  NODE_VERSION: "14.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Cache yarn
      uses: c-hive/gha-yarn-cache@v2

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Run commitlint
      if: "!contains(github.event.commits[0].message, '[skip ci]')"
      run: yarn commitlint --from=HEAD~1

    - name: Run lint
      run: yarn lint

    - name: Run tests
      run: yarn test:ci

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Set up Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Cache yarn
      uses: c-hive/gha-yarn-cache@v2

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Release new version
      env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release

  rebase-dev:
    needs: [build, release]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get current branch name
      id: branch-name
      uses: tj-actions/branch-names@v5

    - name: Rebase ${{ steps.branch-name.outputs.current_branch }} onto dev
      uses: ./.github/actions/rebase-branch
      with:
        source: ${{ steps.branch-name.outputs.current_branch }}
        target: dev

    - name: Push changes to the branch dev
      uses: CasperWA/push-protected@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
        branch: dev
        force: true
        unprotect_reviews: true
